service: datalake

custom:
  project: dataplattform
  stage: ${opt:stage, self:provider.stage}
  service: ${self:custom.stage}-${self:service}


provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.service}
  deploymentBucket: #provide a bucket name to where serverless assets should to be uploaded
    name: dataplattform-v2-deploymentbucket

  tags:
    project: dataplattform
    layer: infrastructure
  stackTags: #sets CloudFormation stack tags
    project: dataplattform
    layer: infrastructure

resources:
  Resources:
    DataLake:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.service}-datalake
        VersioningConfiguration:
          Status: Enabled #keeps different versions of object if overwrited/updated
        PublicAccessBlockConfiguration: #blocks any public access to s3 bucket
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True


  Outputs:
    DataLakeArn:
      Value:
        Fn::GetAtt:
          - DataLake
          - Arn
      Export:
        Name: ${self:custom.service}-datalakeArn #should change this to ${self:custom.service}-datalakeArn
